[build]
  # O comando de build que o Netlify irá executar
  command = "npm run build"
  
  # A pasta onde o Vite gera os arquivos prontos para produção
  publish = "dist"

# Configuração para evitar erros 404 ao atualizar a página (Essencial para SPAs em React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
