import { BankAccount, Transaction, Budget, TransactionCategory } from './types';

export const INITIAL_ACCOUNTS: BankAccount[] = [
  {
    id: 'acc-1',
    name: 'Conta Corrente Itaú',
    type: 'checking',
    balance: 3450.80,
    institution: 'Itaú',
    syncStatus: 'synced',
    lastSynced: 'Hoje, 10:24',
    accountNumber: 'Ag: 0455 C/C: 12345-6',
    color: 'from-orange-500 to-amber-600',
  },
  {
    id: 'acc-2',
    name: 'NuConta',
    type: 'savings',
    balance: 8900.50,
    institution: 'Nubank',
    syncStatus: 'synced',
    lastSynced: 'Hoje, 09:15',
    accountNumber: 'Ag: 0001 C/C: 987654-3',
    color: 'from-purple-600 to-indigo-700',
  },
  {
    id: 'acc-3',
    name: 'Carteira (Dinheiro)',
    type: 'cash',
    balance: 220.00,
    institution: 'Carteira',
    syncStatus: 'disconnected',
    color: 'from-slate-600 to-slate-800',
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    description: 'Supermercado Pão de Açúcar',
    amount: -342.50,
    type: 'expense',
    category: 'Alimentação',
    date: '2026-07-20',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-2',
    description: 'Salário Google Inc.',
    amount: 12500.00,
    type: 'income',
    category: 'Salário',
    date: '2026-07-05',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-3',
    description: 'Assinatura Netflix',
    amount: -55.90,
    type: 'expense',
    category: 'Lazer',
    date: '2026-07-18',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-4',
    description: 'Posto Shell Combustível',
    amount: -150.00,
    type: 'expense',
    category: 'Transporte',
    date: '2026-07-19',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-5',
    description: 'Aluguel do Apartamento',
    amount: -2200.00,
    type: 'expense',
    category: 'Moradia',
    date: '2026-07-10',
    accountId: 'acc-1',
    isSynced: false,
  },
  {
    id: 'tx-6',
    description: 'Rendimento CDB 100% CDI',
    amount: 87.45,
    type: 'income',
    category: 'Investimentos',
    date: '2026-07-15',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-7',
    description: 'Consulta Odontológica',
    amount: -250.00,
    type: 'expense',
    category: 'Saúde',
    date: '2026-07-12',
    accountId: 'acc-3',
    isSynced: false,
  },
  {
    id: 'tx-8',
    description: 'Curso de Inglês Online',
    amount: -180.00,
    type: 'expense',
    category: 'Educação',
    date: '2026-07-08',
    accountId: 'acc-1',
    isSynced: false,
  },
  // Junho 2026
  {
    id: 'tx-jun-1',
    description: 'Salário Google Inc.',
    amount: 12500.00,
    type: 'income',
    category: 'Salário',
    date: '2026-06-05',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-jun-2',
    description: 'Rendimento CDB 100% CDI',
    amount: 75.20,
    type: 'income',
    category: 'Investimentos',
    date: '2026-06-15',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-jun-3',
    description: 'Aluguel do Apartamento',
    amount: -2200.00,
    type: 'expense',
    category: 'Moradia',
    date: '2026-06-10',
    accountId: 'acc-1',
    isSynced: false,
  },
  {
    id: 'tx-jun-4',
    description: 'Supermercado Pão de Açúcar',
    amount: -450.00,
    type: 'expense',
    category: 'Alimentação',
    date: '2026-06-12',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-jun-5',
    description: 'Jantar Coco Bambu',
    amount: -180.00,
    type: 'expense',
    category: 'Lazer',
    date: '2026-06-18',
    accountId: 'acc-1',
    isSynced: false,
  },
  {
    id: 'tx-jun-6',
    description: 'Uber Viagem',
    amount: -35.50,
    type: 'expense',
    category: 'Transporte',
    date: '2026-06-20',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-jun-7',
    description: 'Droga Raia Medicamentos',
    amount: -82.10,
    type: 'expense',
    category: 'Saúde',
    date: '2026-06-25',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  // Maio 2026
  {
    id: 'tx-may-1',
    description: 'Salário Google Inc.',
    amount: 12500.00,
    type: 'income',
    category: 'Salário',
    date: '2026-05-05',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-may-2',
    description: 'Aluguel do Apartamento',
    amount: -2200.00,
    type: 'expense',
    category: 'Moradia',
    date: '2026-05-10',
    accountId: 'acc-1',
    isSynced: false,
  },
  {
    id: 'tx-may-3',
    description: 'Supermercado Carrefour',
    amount: -520.00,
    type: 'expense',
    category: 'Alimentação',
    date: '2026-05-12',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-may-4',
    description: 'Geladeira Nova Frost Free',
    amount: -5500.00,
    type: 'expense',
    category: 'Moradia',
    date: '2026-05-14',
    accountId: 'acc-1',
    isSynced: false,
  },
  {
    id: 'tx-may-5',
    description: 'Viagem Porto de Galinhas',
    amount: -4000.00,
    type: 'expense',
    category: 'Lazer',
    date: '2026-05-20',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-may-6',
    description: 'Curso UX/UI Design',
    amount: -1200.00,
    type: 'expense',
    category: 'Educação',
    date: '2026-05-25',
    accountId: 'acc-1',
    isSynced: false,
  },
  // Abril 2026
  {
    id: 'tx-apr-1',
    description: 'Salário Google Inc.',
    amount: 12500.00,
    type: 'income',
    category: 'Salário',
    date: '2026-04-05',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-apr-2',
    description: 'PIX Venda Monitor Antigo',
    amount: 500.00,
    type: 'income',
    category: 'Outros',
    date: '2026-04-22',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-apr-3',
    description: 'Aluguel do Apartamento',
    amount: -2200.00,
    type: 'expense',
    category: 'Moradia',
    date: '2026-04-10',
    accountId: 'acc-1',
    isSynced: false,
  },
  {
    id: 'tx-apr-4',
    description: 'Supermercado Pão de Açúcar',
    amount: -380.00,
    type: 'expense',
    category: 'Alimentação',
    date: '2026-04-12',
    accountId: 'acc-1',
    isSynced: true,
    bankName: 'Itaú',
  },
  {
    id: 'tx-apr-5',
    description: 'Ingressos Show Rock in Rio',
    amount: -600.00,
    type: 'expense',
    category: 'Lazer',
    date: '2026-04-18',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  },
  {
    id: 'tx-apr-6',
    description: 'Abastecimento Carro',
    amount: -120.00,
    type: 'expense',
    category: 'Transporte',
    date: '2026-04-20',
    accountId: 'acc-2',
    isSynced: true,
    bankName: 'Nubank',
  }
];

export const INITIAL_BUDGETS: Budget[] = [
  { category: 'Alimentação', limit: 1200, spent: 342.50 },
  { category: 'Transporte', limit: 500, spent: 150.00 },
  { category: 'Lazer', limit: 400, spent: 55.90 },
  { category: 'Moradia', limit: 2500, spent: 2200.00 },
  { category: 'Saúde', limit: 300, spent: 250.00 },
  { category: 'Educação', limit: 500, spent: 180.00 }
];

export const CATEGORIES_CONFIG: Record<
  TransactionCategory,
  { color: string; bgColor: string; icon: string }
> = {
  Alimentação: { color: 'text-orange-400', bgColor: 'bg-orange-950/40 border-orange-900/30', icon: 'Utensils' },
  Transporte: { color: 'text-blue-400', bgColor: 'bg-blue-950/40 border-blue-900/30', icon: 'Car' },
  Moradia: { color: 'text-purple-400', bgColor: 'bg-purple-950/40 border-purple-900/30', icon: 'Home' },
  Lazer: { color: 'text-pink-400', bgColor: 'bg-pink-950/40 border-pink-900/30', icon: 'Sparkles' },
  Saúde: { color: 'text-rose-400', bgColor: 'bg-rose-950/40 border-rose-900/30', icon: 'Heart' },
  Educação: { color: 'text-amber-400', bgColor: 'bg-amber-950/40 border-amber-900/30', icon: 'BookOpen' },
  Salário: { color: 'text-emerald-400', bgColor: 'bg-emerald-950/40 border-emerald-900/30', icon: 'DollarSign' },
  Investimentos: { color: 'text-cyan-400', bgColor: 'bg-cyan-950/40 border-cyan-900/30', icon: 'TrendingUp' },
  Outros: { color: 'text-zinc-400', bgColor: 'bg-zinc-800/50 border-zinc-700/30', icon: 'HelpCircle' },
};

// Simulated bank transactions for bank integration flow
export const BANK_SIMULATION_TRANSACTIONS: Record<string, Omit<Transaction, 'id' | 'accountId'>[]> = {
  Itaú: [
    {
      description: 'Padaria Bella Paulista',
      amount: -42.80,
      type: 'expense',
      category: 'Alimentação',
      date: '2026-07-21',
      isSynced: true,
      bankName: 'Itaú',
    },
    {
      description: 'Transferência Recebida PIX José',
      amount: 450.00,
      type: 'income',
      category: 'Outros',
      date: '2026-07-20',
      isSynced: true,
      bankName: 'Itaú',
    },
    {
      description: 'Uber *Viagem',
      amount: -24.90,
      type: 'expense',
      category: 'Transporte',
      date: '2026-07-20',
      isSynced: true,
      bankName: 'Itaú',
    }
  ],
  Nubank: [
    {
      description: 'Restaurante Sabor & Arte',
      amount: -89.90,
      type: 'expense',
      category: 'Alimentação',
      date: '2026-07-21',
      isSynced: true,
      bankName: 'Nubank',
    },
    {
      description: 'Estacionamento Shopping',
      amount: -22.00,
      type: 'expense',
      category: 'Transporte',
      date: '2026-07-20',
      isSynced: true,
      bankName: 'Nubank',
    },
    {
      description: 'Assinatura Spotify',
      amount: -34.90,
      type: 'expense',
      category: 'Lazer',
      date: '2026-07-19',
      isSynced: true,
      bankName: 'Nubank',
    }
  ],
  Bradesco: [
    {
      description: 'Reembolso Seguro Saúde',
      amount: 320.00,
      type: 'income',
      category: 'Saúde',
      date: '2026-07-21',
      isSynced: true,
      bankName: 'Bradesco',
    },
    {
      description: 'Cobrança Sem Parar',
      amount: -85.00,
      type: 'expense',
      category: 'Transporte',
      date: '2026-07-19',
      isSynced: true,
      bankName: 'Bradesco',
    },
    {
      description: 'Compra Decathlon Esportes',
      amount: -299.90,
      type: 'expense',
      category: 'Lazer',
      date: '2026-07-18',
      isSynced: true,
      bankName: 'Bradesco',
    }
  ],
  'Banco do Brasil': [
    {
      description: 'Rendimento Ourocap BB',
      amount: 150.00,
      type: 'income',
      category: 'Investimentos',
      date: '2026-07-20',
      isSynced: true,
      bankName: 'Banco do Brasil',
    },
    {
      description: 'Tarifa Mensalidade Conta',
      amount: -29.90,
      type: 'expense',
      category: 'Outros',
      date: '2026-07-18',
      isSynced: true,
      bankName: 'Banco do Brasil',
    },
    {
      description: 'Livraria Cultura',
      amount: -120.00,
      type: 'expense',
      category: 'Educação',
      date: '2026-07-15',
      isSynced: true,
      bankName: 'Banco do Brasil',
    }
  ],
  'C6 Bank': [
    {
      description: 'Supermercado Mambo',
      amount: -180.50,
      type: 'expense',
      category: 'Alimentação',
      date: '2026-07-21',
      isSynced: true,
      bankName: 'C6 Bank',
    },
    {
      description: 'Investimento CDB Pós C6',
      amount: -500.00,
      type: 'expense',
      category: 'Investimentos',
      date: '2026-07-20',
      isSynced: true,
      bankName: 'C6 Bank',
    },
    {
      description: 'Estorno Amazon Prime',
      amount: 159.90,
      type: 'income',
      category: 'Outros',
      date: '2026-07-19',
      isSynced: true,
      bankName: 'C6 Bank',
    }
  ],
  PicPay: [
    {
      description: 'Pizzaria Bráz',
      amount: -110.00,
      type: 'expense',
      category: 'Alimentação',
      date: '2026-07-21',
      isSynced: true,
      bankName: 'PicPay',
    },
    {
      description: 'Rendimento CDI PicPay',
      amount: 12.45,
      type: 'income',
      category: 'Investimentos',
      date: '2026-07-20',
      isSynced: true,
      bankName: 'PicPay',
    },
    {
      description: 'PIX Recebido Carlos André',
      amount: 250.00,
      type: 'income',
      category: 'Outros',
      date: '2026-07-18',
      isSynced: true,
      bankName: 'PicPay',
    }
  ]
};
